/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xd_adhocroute_nativehelper_NativeTask */

#ifndef _Included_com_xd_adhocroute_nativehelper_NativeTask
#define _Included_com_xd_adhocroute_nativehelper_NativeTask
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_xd_adhocroute_nativehelper_NativeTask
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xd_adhocroute1s_nativehelper_NativeTask_runCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_xd_adhocroute_nativehelper_NativeTask
 * Method:    killProcess
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xd_adhocroute1s_nativehelper_NativeTask_killProcess
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
