/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_xd_net_speex_Speex */

#ifndef _Included_edu_xd_net_speex_Speex
#define _Included_edu_xd_net_speex_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_xd_net_speex_Speex_DEFAULT_COMPRESSION
#define edu_xd_net_speex_Speex_DEFAULT_COMPRESSION 8L
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    open
 * Signature: (I)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_open(JNIEnv *, jobject,
		jint);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_getFrameSize(JNIEnv *,
		jobject);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_decode(JNIEnv *, jobject,
		jbyteArray, jshortArray, jint);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_encode(JNIEnv *, jobject,
		jshortArray, jint, jbyteArray, jint);

/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    close
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_edu_xd_net_speex_Speex_close(JNIEnv *, jobject);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    echoinit
 * Signature: (II)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_echoinit(JNIEnv *, jobject,
		jint, jint);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    echoplayback
 * Signature: ([S)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_echoplayback(JNIEnv *,
		jobject, jshortArray);
/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    echocapture
 * Signature: ([S[S)I
 */JNIEXPORT jint JNICALL Java_com_xd_wifimultihop_business_speex_Speex_echocapture(JNIEnv *,
		jobject, jshortArray, jshortArray);

/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    echoclose
 * Signature: ()V
 */JNIEXPORT void JNICALL Java_com_xd_wifimultihop_business_speex_Speex_echoclose(JNIEnv *,
		jobject);

/*
 * Class:     edu_xd_net_speex_Speex
 * Method:    echocancel
 * Signature: ()V
 */JNIEXPORT void JNICALL com_xd_wifimultihop_business_speex_Speex_echocancel(JNIEnv *,
		jobject, jshortArray, jshortArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
